LATEXOPT=--shell-escape

LATEXMK=latexmk

########################################################################
# latexmk can not delete specific file whose base name
# is different from main tex file base name.

# Handle pdfa.xmpi file
# generated by pdfx package.
#
# After processing,
# the local directory contains a file named such as pdfa.xmpi or pdfe.xmpi
# or pdfx.xmpi according to the PDF variant desired.
# This file is the complete XMP Metadata packet.
# It can be checked for validity, using an online validator,
# such as at www.pdflib.com.
# veraPDF [28] is Open Source software providing validation for PDF/A,
# and other checkers useful in a PDF/A production setting.
# See pdfx documentation file pdfx.pdf,
# Version 1.6.3, 2019/02/27, section 2.2, page 6.
XMPI_FILE=pdfa.xmpi

# Handle biblatex datamodel files
# generated by main tex file to add new entry fields.
#
# The files have the extension dbx.
#
# Redefining the data model can be done in several places.
# Style authors can create a .dbx file which contains
# the data model macros required
# and this will be loaded automatically when using
# the biblatex package style option
# by looking for a file named after the style with a .dbx extension
# (just like the .cbx and .bbx files for a style).
# If the style option is not used but rather the citestyle and bibstyle options,
# then the package will try to load .dbx files
# called <citestyle>.dbx and <bibstyle>.dbx.
# Alternatively, the name of the data model file can be different
# from any of the style option names by specifying the name
# (without .dbx extension) to the package datamodel option.
# After loading the style data model file, biblatex then loads, if present,
# a users biblatex-dm.cfg which should be put somewhere biblatex can find it,
# just like the main configuration file biblatex.cfg.
# To summarise, the data model is determined by adding to the data model
# from each of these locations, in order:
# blx-dm.def→
#   <datamodel option>.dbx →
#     <style option>.dbx →
#       <citestyle option>.dbx and <bibstyle option>.dbx →
#         biblatex-dm.cfg
# See biblatex documentation file biblatex.pdf,
# 3.12, 2018/10/30, section 4.5.4, page 194.
BIBLATEX_DATAMODEL_FILE=specific_fields_definition.dbx

# inkscapepath (opt.)
# The option inkscapepath specifies,
# where the resulting files of the Inkscape export should be located.
# The subfolder ./svg-inkscape/ within the current working directory is used
# by default (inkscapepath=basesubdir).
# See svg documentation file svg.pdf,
# v2.02b, 2018/11/12, section 2.2, page 4.
SVG_INKSCAPE_PATH=svg-inkscape

all:
	$(LATEXMK)

clean:
	$(LATEXMK) -c

clean-all:
	$(LATEXMK) -C

.PHONY: clean clean-all all